/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type YoutubeBlock = {
  _type: 'youtubeBlock'
  heading?: {
    text?: string
    level?: 2 | 3 | 4 | 5
  }
  url?: string
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
  }
}

export type TestimonialBlock = {
  _type: 'testimonialBlock'
  heading?: {
    text?: string
    level?: 2 | 3 | 4 | 5
  }
  quote?: string
  author?: {
    name?: string
    title?: string
    image?: CustomImage
  }
  rating?: number
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
  }
}

export type StatsBlock = {
  _type: 'statsBlock'
  heading?: {
    text?: string
    level?: 2 | 3 | 4 | 5
  }
  stats?: Array<{
    value?: string
    title?: string
    _type: 'stat'
    _key: string
  }>
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
  }
}

export type SlideshowBlock = {
  _type: 'slideshowBlock'
  heading?: {
    text?: string
    level?: 2 | 3 | 4 | 5
  }
  images?: Array<
    {
      _key: string
    } & CustomImage
  >
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
    autoplay?: boolean
    interval?: number
  }
}

export type PostsListBlock = {
  _type: 'postsListBlock'
  postType?: 'posts' | 'pages'
  limit?: number
  order?: 'newest' | 'oldest'
  showPagination?: boolean
}

export type PageHeaderBlock = {
  _type: 'pageHeaderBlock'
  title?: string
  subtitle?: string
}

export type LogoParadeBlock = {
  _type: 'logoParadeBlock'
  heading?: {
    text?: string
    level?: 2 | 3 | 4 | 5
  }
  images?: Array<
    {
      _key: string
    } & CustomImage
  >
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
  }
}

export type ImageGridBlock = {
  _type: 'imageGridBlock'
  heading?: {
    text?: string
    level?: 2 | 3 | 4 | 5
  }
  images?: Array<{
    customImage?: CustomImage
    _key: string
  }>
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
    columns?: number
  }
}

export type HeroBlock = {
  _type: 'heroBlock'
  image?: CustomImage
  valueProposition?: Array<
    | ({
        _key: string
      } & CustomImage)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          linkType?: 'href' | 'page' | 'post'
          href?: string
          page?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'page'
          }
          post?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'post'
          }
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
  >
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
  }
}

export type GalleryBlock = {
  _type: 'galleryBlock'
  heading?: {
    text?: string
    level?: 2 | 3 | 4 | 5
  }
  images?: Array<
    {
      _key: string
    } & CustomImage
  >
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
    width?: 'full' | 'limited'
  }
}

export type FeaturesBlock = {
  _type: 'featuresBlock'
  heading?: {
    text?: string
    level?: 2 | 3 | 4 | 5
  }
  features?: Array<{
    icon?: CustomImage
    title?: string
    description?: string
    _key: string
  }>
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
    columns?: number
    layout?: 'default' | 'cards'
  }
}

export type ContentBlock = {
  _type: 'contentBlock'
  content?: Array<
    | ({
        _key: string
      } & CustomImage)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          linkType?: 'href' | 'page' | 'post'
          href?: string
          page?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'page'
          }
          post?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'post'
          }
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
  >
  align?: 'start' | 'center' | 'end'
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
  }
}

export type CarouselBlock = {
  _type: 'carouselBlock'
  heading?: {
    text?: string
    level?: 2 | 3 | 4 | 5
  }
  images?: Array<{
    image?: CustomImage
    body?: Array<
      | ({
          _key: string
        } & CustomImage)
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            linkType?: 'href' | 'page' | 'post'
            href?: string
            page?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'page'
            }
            post?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'post'
            }
            openInNewTab?: boolean
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
    >
    _key: string
  }>
  autoplay?: boolean
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
  }
}

export type CallToActionBlock = {
  _type: 'callToActionBlock'
  body?: Array<
    | ({
        _key: string
      } & CustomImage)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          linkType?: 'href' | 'page' | 'post'
          href?: string
          page?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'page'
          }
          post?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'post'
          }
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
  >
  formDisplay?: 'inline' | 'modal'
  buttonText?: string
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
    layout?: 'default' | 'form'
  }
}

export type BentoBlock = {
  _type: 'bentoBlock'
  heading?: {
    text?: string
    level?: 2 | 3 | 4 | 5
  }
  grid?: {
    items?: Array<{
      content?: Array<
        | ({
            _key: string
          } & CustomImage)
        | {
            children?: Array<{
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }>
            style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
            listItem?: 'bullet' | 'number'
            markDefs?: Array<{
              linkType?: 'href' | 'page' | 'post'
              href?: string
              page?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
              post?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'post'
              }
              openInNewTab?: boolean
              _type: 'link'
              _key: string
            }>
            level?: number
            _type: 'block'
            _key: string
          }
      >
      options?: {
        blockTheme?: 'PRIMARY' | 'SECONDARY' | 'ACCENT' | 'MUTED' | 'TRANSPARENT'
        colspan?: 'one' | 'two' | 'three' | 'four'
      }
      _key: string
    }>
    options?: {
      columns?: 'one' | 'two' | 'three' | 'four'
      noGap?: boolean
    }
  }
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
    offset?: boolean
    reverse?: boolean
  }
}

export type AdvancedListBlock = {
  _type: 'advancedListBlock'
  heading?: {
    text?: string
    level?: 2 | 3 | 4 | 5
  }
  listItems?: Array<{
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    body?: Array<
      | ({
          _key: string
        } & CustomImage)
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            linkType?: 'href' | 'page' | 'post'
            href?: string
            page?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'page'
            }
            post?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'post'
            }
            openInNewTab?: boolean
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
    >
    _type: 'listItem'
    _key: string
  }>
  options?: {
    id?: string
    style?: 'DEFAULT' | 'HOME' | 'FEATURES'
    textAlign?: 'left' | 'center' | 'right'
    vAlign?: 'top' | 'center' | 'bottom'
    blockTheme?: 'DEFAULT' | 'PRIMARY' | 'SECONDARY' | 'MUTED' | 'ACCENT'
    bgFullWidth?: boolean
    type?: 'bullet' | 'number'
    orientation?: 'horizontal' | 'vertical'
  }
}

export type NavItem = {
  _type: 'navItem'
  linkType?: 'href' | 'page' | 'dropdown'
  dropdown?: {
    label?: string
    items?: Array<
      {
        _key: string
      } & NavItem
    >
  }
  href?: string
  page?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'page'
  }
  openInNewTab?: boolean
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'page'
  }
  post?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'post'
  }
  openInNewTab?: boolean
}

export type BlockContent = Array<
  | ({
      _key: string
    } & CustomImage)
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
        post?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'post'
        }
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
>

export type Home = {
  _id: string
  _type: 'home'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & AdvancedListBlock)
    | ({
        _key: string
      } & BentoBlock)
    | ({
        _key: string
      } & CallToActionBlock)
    | ({
        _key: string
      } & CarouselBlock)
    | ({
        _key: string
      } & ContentBlock)
    | ({
        _key: string
      } & FeaturesBlock)
    | ({
        _key: string
      } & GalleryBlock)
    | ({
        _key: string
      } & HeroBlock)
    | ({
        _key: string
      } & ImageGridBlock)
    | ({
        _key: string
      } & LogoParadeBlock)
    | ({
        _key: string
      } & PageHeaderBlock)
    | ({
        _key: string
      } & PostsListBlock)
    | ({
        _key: string
      } & SlideshowBlock)
    | ({
        _key: string
      } & StatsBlock)
    | ({
        _key: string
      } & TestimonialBlock)
    | ({
        _key: string
      } & YoutubeBlock)
  >
  gallery?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    altText?: string
    _type: 'image'
    _key: string
  }>
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  heading?: string
  subheading?: string
  showHero?: boolean
  hero?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: BlockContent
  coverImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  pageBuilder?: Array<
    | ({
        _key: string
      } & AdvancedListBlock)
    | ({
        _key: string
      } & BentoBlock)
    | ({
        _key: string
      } & CallToActionBlock)
    | ({
        _key: string
      } & CarouselBlock)
    | ({
        _key: string
      } & ContentBlock)
    | ({
        _key: string
      } & FeaturesBlock)
    | ({
        _key: string
      } & GalleryBlock)
    | ({
        _key: string
      } & HeroBlock)
    | ({
        _key: string
      } & ImageGridBlock)
    | ({
        _key: string
      } & LogoParadeBlock)
    | ({
        _key: string
      } & PageHeaderBlock)
    | ({
        _key: string
      } & PostsListBlock)
    | ({
        _key: string
      } & SlideshowBlock)
    | ({
        _key: string
      } & StatsBlock)
    | ({
        _key: string
      } & TestimonialBlock)
    | ({
        _key: string
      } & YoutubeBlock)
  >
  gallery?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    altText?: string
    _type: 'image'
    _key: string
  }>
}

export type CustomImage = {
  _type: 'customImage'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  altText?: string
  metadata?: {
    width?: number
    height?: number
    circle?: boolean
    showFigure?: boolean
  }
  figure?: {
    caption?: BlockContent
    photoCredit?: {
      credit?: string
      creditLink?: string
    }
  }
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  content?: BlockContent
  description?: BlockContent
  coverImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'person'
  }
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName?: string
  lastName?: string
  picture?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  showTitle?: boolean
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  siteLogo?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  navigation?: {
    desktop?: Array<
      {
        _key: string
      } & NavItem
    >
    mobile?: Array<
      {
        _key: string
      } & NavItem
    >
    footer?: Array<
      {
        _key: string
      } & NavItem
    >
  }
  organizations?: Array<{
    label?: string
    name?: string
    businessType?:
      | 'AnimalShelter'
      | 'ArchiveOrganization'
      | 'AutomotiveBusiness'
      | 'ChildCare'
      | 'Dentist'
      | 'DryCleaningOrLaundry'
      | 'Electrician'
      | 'EmergencyService'
      | 'EmploymentAgency'
      | 'EntertainmentBusiness'
      | 'FinancialService'
      | 'FoodEstablishment'
      | 'GovernmentOffice'
      | 'HealthAndBeautyBusiness'
      | 'HomeAndConstructionBusiness'
      | 'InternetCafe'
      | 'LegalService'
      | 'Library'
      | 'LodgingBusiness'
      | 'MedicalBusiness'
      | 'ProfessionalService'
      | 'RadioStation'
      | 'RealEstateAgent'
      | 'RecyclingCenter'
      | 'SelfStorage'
      | 'ShoppingCenter'
      | 'SportsActivityLocation'
      | 'Store'
      | 'TelevisionStation'
      | 'TouristInformationCenter'
      | 'TravelAgency'
    homepage?: string
    address?: {
      street1?: string
      street2?: string
      city?: string
      state?: string
      zip?: string
    }
    phone?: string
    email?: string
    gallery?: Array<{
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      altText?: string
      _type: 'image'
      _key: string
    }>
    _type: 'organization'
    _key: string
  }>
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
  }
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message?: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | YoutubeBlock
  | TestimonialBlock
  | StatsBlock
  | SlideshowBlock
  | PostsListBlock
  | PageHeaderBlock
  | LogoParadeBlock
  | ImageGridBlock
  | HeroBlock
  | GalleryBlock
  | FeaturesBlock
  | ContentBlock
  | CarouselBlock
  | CallToActionBlock
  | BentoBlock
  | AdvancedListBlock
  | NavItem
  | Link
  | BlockContent
  | Home
  | Page
  | CustomImage
  | Post
  | Person
  | Settings
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
